
(function(){
'use strict';
const root=window.CABW_CONTRACTS_DATA||{records:[],summary:{}}; const records=Array.isArray(root.records)?root.records:[]; const summary=root.summary||{};
const $=(s,c)=> (c||document).querySelector(s); const $all=(s,c)=>Array.from((c||document).querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>'US$ '+Number(v||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const num=v=>Number(v||0).toLocaleString('pt-BR');
function selected(sel){if(!sel)return []; return Array.from(sel.selectedOptions).map(o=>o.value).filter(Boolean);}
function unique(a){return Array.from(new Set(a.filter(v=>v!==undefined&&v!==null&&String(v).trim()!==''))).sort((a,b)=>String(a).localeCompare(String(b),'pt-BR'));}
function fillMulti(sel, vals){if(!sel)return; const old=selected(sel); sel.multiple=true; sel.size=Math.min(6, Math.max(3, vals.length+1)); sel.classList.add('cabw-multi-select'); sel.innerHTML=vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join(''); old.forEach(v=>{const o=Array.from(sel.options).find(o=>o.value===v); if(o)o.selected=true;});}
function dateBr(s){if(!s)return '—'; const [y,m,d]=String(s).split('-'); return d&&m&&y?`${d}/${m}/${y}`:'—';}
function daysToEnd(r){if(!r.dataFinal)return null; const end=new Date(r.dataFinal+'T00:00:00'); const now=new Date(); now.setHours(0,0,0,0); return Math.ceil((end-now)/(1000*60*60*24));}
function vigenciaBucket(r){const d=daysToEnd(r); if(d===null||Number.isNaN(d)) return 'Sem data final'; if(d<0) return 'Vigência expirada'; if(d<=90) return 'Vencimento em até 90 dias'; if(d<=150) return 'Vencimento entre 90 e 150 dias'; return 'Vencimento acima de 150 dias';}
function risk(r){const d=daysToEnd(r); if(d===null||Number.isNaN(d)) return ''; if(d<0)return 'VENCIDO'; if(d<=90)return 'RISCO'; return '';}
function catRows(cat){return records.filter(r=>!cat||r.category===cat);}
function agg(rows){return {count:rows.length,value:rows.reduce((a,r)=>a+Number(r.valorContrato||0),0),paid:rows.reduce((a,r)=>a+Number(r.totalEmpenhadoUsd||0),0),billed:rows.reduce((a,r)=>a+Number(r.totalFaturadoUsd||0),0),available:rows.reduce((a,r)=>a+Number(r.valorAEmpenhar||0),0)};}
function filters(){return {numero:selected($('#filterNumeroContrato')), empresa:selected($('#filterEmpresa')), unidade:selected($('#filterUnidade')), gc:selected($('#filterGrandeComando')), ordenador:selected($('#filterOrdenador')), acao:selected($('#filterAcao')), moeda:selected($('#filterMoeda')), status:selected($('#filterStatus')), search:($('#filterContratoSearch')?.value||'').trim().toLowerCase()};}
function has(sel,val){return !sel.length||sel.includes(val||'');}
function rowMatches(r,f,cat){const ordVal = cat==='finalisticos' ? r.tipoOrdenacao : r.ordenadorDespesa; const hay=[r.contrato,r.numero,r.empresa,r.objetoResumo,r.unidade,r.grandComando,r.acao,r.cage,ordVal].join(' ').toLowerCase(); return has(f.numero,r.numero)&&has(f.empresa,r.empresa)&&has(f.unidade,r.unidade)&&has(f.gc,r.grandComando)&&has(f.ordenador,ordVal)&&has(f.acao,r.acao)&&has(f.moeda,r.moeda)&&has(f.status,vigenciaBucket(r))&&(!f.search||hay.includes(f.search));}
function populateFilters(rows,cat){fillMulti($('#filterNumeroContrato'), unique(rows.map(r=>r.numero))); fillMulti($('#filterEmpresa'), unique(rows.map(r=>r.empresa))); fillMulti($('#filterUnidade'), unique(rows.map(r=>r.unidade))); fillMulti($('#filterGrandeComando'), unique(rows.map(r=>r.grandComando))); fillMulti($('#filterOrdenador'), cat==='finalisticos' ? ['Ordenação de despesas pela CABW','Ordenação de Despesas pela OM Requisitante'] : unique(rows.map(r=>r.ordenadorDespesa))); fillMulti($('#filterAcao'), unique(rows.map(r=>r.acao))); fillMulti($('#filterMoeda'), unique(rows.map(r=>r.moeda))); fillMulti($('#filterStatus'), ['Vencimento acima de 150 dias','Vencimento entre 90 e 150 dias','Vencimento em até 90 dias','Vigência expirada','Sem data final']);}
function drawChart(rows){const el=$('#contractsValueChart'); if(!el)return; const a=agg(rows); if(window.Plotly){Plotly.newPlot(el,[{type:'bar',x:['Valor contratado','Empenhado','Faturado','Disponível p/ empenho'],y:[a.value,a.paid,a.billed,a.available],text:[money(a.value),money(a.paid),money(a.billed),money(a.available)],textposition:'auto',marker:{color:['#003b7a','#0e63b6','#f5c400','#4c6a92']}}],{height:360,margin:{l:80,r:20,t:20,b:90},yaxis:{title:'US$'}},{displayModeBar:false,responsive:true});}else{el.innerHTML='<p>Plotly não carregado.</p>';}}
function renderOverview(){const rootEl=document.querySelector('[data-contract-overview]'); if(!rootEl)return; const all=agg(records); $('[data-all-contracts-count]')&&($('[data-all-contracts-count]').textContent=num(all.count)); $('[data-all-contracts-paid]')&&($('[data-all-contracts-paid]').textContent=money(all.paid)+' empenhados'); $all('[data-contract-summary]').forEach(card=>{const cat=card.getAttribute('data-contract-summary'); const a=agg(catRows(cat)); $('[data-summary-count]',card)&&($('[data-summary-count]',card).textContent=num(a.count)); $('[data-summary-value]',card)&&($('[data-summary-value]',card).textContent=money(a.value)); $('[data-summary-paid]',card)&&($('[data-summary-paid]',card).textContent=money(a.paid));});}
function renderPanel(){const cat=document.body.getAttribute('data-contract-category'); if(!cat)return; const base=catRows(cat); $('#contract-section-title')&&($('#contract-section-title').textContent={administrativos:'Contratos Administrativos',finalisticos:'Contratos Finalísticos',fms:'FMS (Foreign Military Sales)'}[cat]||'Contratos'); populateFilters(base,cat); function refresh(){const f=filters(); const rows=base.filter(r=>rowMatches(r,f,cat)); const a=agg(rows); $('[data-kpi="count"]')&&($('[data-kpi="count"]').textContent=num(a.count)); $('[data-kpi="value"]')&&($('[data-kpi="value"]').textContent=money(a.value)); $('[data-kpi="paidUsd"]')&&($('[data-kpi="paidUsd"]').textContent=money(a.paid)); $('[data-kpi="billedUsd"]')&&($('[data-kpi="billedUsd"]').textContent=money(a.billed)); const count=$('#contractsTableCount'); if(count) count.textContent=num(rows.length)+' contrato(s)'; const tb=$('#contractsTable tbody'); if(tb) tb.innerHTML=rows.map(r=>`<tr class="${risk(r)?'contract-risk-row':''}"><td>${esc(r.contrato)}</td><td>${esc(r.numero)}</td><td>${esc(r.unidade)}</td><td>${esc(cat==='finalisticos'?r.tipoOrdenacao:r.ordenadorDespesa)}</td><td>${esc(r.grandComando)}</td><td>${esc(r.empresa)}</td><td class="contracts-object-cell">${esc(r.objetoResumo)}</td><td>${esc(r.moeda)}</td><td class="text-right">${money(r.valorContrato)}</td><td class="text-right">${money(r.totalEmpenhadoUsd)}</td><td class="text-right">${money(r.totalFaturadoUsd)}</td><td class="text-right">${money(r.valorAEmpenhar)}</td><td>${dateBr(r.dataFinal)}</td><td>${esc(vigenciaBucket(r))} ${risk(r)?'<strong class="risk-flag">'+risk(r)+'</strong>':''}</td></tr>`).join(''); drawChart(rows);} $all('#filterNumeroContrato,#filterEmpresa,#filterUnidade,#filterGrandeComando,#filterOrdenador,#filterAcao,#filterMoeda,#filterStatus').forEach(el=>el.addEventListener('change',refresh)); $('#filterContratoSearch')?.addEventListener('input',refresh); $('#resetContractFilters')?.addEventListener('click',()=>{ $all('#filterNumeroContrato,#filterEmpresa,#filterUnidade,#filterGrandeComando,#filterOrdenador,#filterAcao,#filterMoeda,#filterStatus').forEach(sel=>Array.from(sel.options).forEach(o=>o.selected=false)); if($('#filterContratoSearch'))$('#filterContratoSearch').value=''; refresh();}); refresh();}
document.addEventListener('DOMContentLoaded',()=>{try{renderOverview();renderPanel();}catch(e){console.error('CABW contracts panel error',e);}});
})();
