
(function(){
'use strict';
const DATA=window.CABW_CONTRACTS_DATA||{contracts:[],summary:{}}; const BR='pt-BR';
const money=new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
function usd(x){return 'US$ '+money.format(+x||0)}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function byId(id){return document.getElementById(id)} function unique(a){return Array.from(new Set(a.filter(Boolean))).sort((x,y)=>String(x).localeCompare(String(y),'pt-BR'))} function sum(a,k){return a.reduce((s,r)=>s+(+r[k]||0),0)}
function cat(){const t=(document.querySelector('h1')?.textContent||'').toLowerCase(); if(t.includes('administr'))return 'administrativos'; if(t.includes('fms'))return 'fms'; if(t.includes('final'))return 'finalisticos'; return null;}
let state={empresa:[],numero:[],unidade:[],gc:[],ordenador:[],acao:[],moeda:[],vigencia:[],q:''};
function short(s,n=22){s=String(s||'');return s.length>n?s.slice(0,n)+'...':s}
function makeMulti(id, opts, key){const sel=byId(id); if(!sel)return; const parent=sel.parentElement; sel.style.display='none'; const wrap=document.createElement('div'); wrap.className='cabw-multi-dropdown'; wrap.innerHTML='<button type="button" class="multi-toggle cabw-multi-toggle"><span>Todos</span><span>▾</span></button><div class="multi-menu cabw-multi-menu"><div class="cabw-multi-actions"><button type="button" data-act="all">Marcar todas</button><button type="button" data-act="clear">Limpar</button></div></div>'; parent.appendChild(wrap); const menu=wrap.querySelector('.cabw-multi-menu'); opts.forEach(o=>{const lab=document.createElement('label'); lab.className='cabw-multi-option'; lab.innerHTML='<input type="checkbox" value="'+esc(o)+'"><span>'+esc(o)+'</span>'; menu.appendChild(lab);}); const btn=wrap.querySelector('.cabw-multi-toggle'); function update(){const vals=Array.from(menu.querySelectorAll('input:checked')).map(x=>x.value); state[key]=vals; btn.querySelector('span').textContent=vals.length?(vals.length===1?short(vals[0],30):vals.length+' selecionados'):'Todos'; render();} btn.addEventListener('click',e=>{e.stopPropagation();wrap.classList.toggle('is-open')}); menu.addEventListener('change',update); menu.addEventListener('click',e=>{if(e.target.dataset.act==='all'){menu.querySelectorAll('input').forEach(i=>i.checked=true);update()} if(e.target.dataset.act==='clear'){menu.querySelectorAll('input').forEach(i=>i.checked=false);update()}}); document.addEventListener('click',e=>{if(!wrap.contains(e.target))wrap.classList.remove('is-open')});}
function initFilters(){const rows=DATA.contracts.filter(c=>!cat()||c.categoria===cat()); makeMulti('filterEmpresa',unique(rows.map(c=>c.empresa)),'empresa'); makeMulti('filterNumeroContrato',unique(rows.map(c=>c.numero)),'numero'); makeMulti('filterUnidade',unique(rows.map(c=>c.unidade)),'unidade'); makeMulti('filterGrandeComando',unique(rows.map(c=>c.grandeComando)),'gc'); makeMulti('filterOrdenador',unique(rows.map(c=>c.ordenador)),'ordenador'); makeMulti('filterAcao',unique(rows.map(c=>c.acao)),'acao'); makeMulti('filterMoeda',unique(rows.map(c=>c.moeda)),'moeda'); makeMulti('filterStatus',unique(rows.map(c=>c.vigencia)),'vigencia'); const q=byId('filterContratoSearch'); if(q)q.addEventListener('input',()=>{state.q=q.value.toLowerCase();render()}); const rst=byId('resetContractFilters'); if(rst)rst.addEventListener('click',()=>{document.querySelectorAll('.cabw-multi-dropdown input').forEach(i=>i.checked=false); state={empresa:[],numero:[],unidade:[],gc:[],ordenador:[],acao:[],moeda:[],vigencia:[],q:''}; if(q)q.value=''; document.querySelectorAll('.cabw-multi-toggle span:first-child').forEach(s=>s.textContent='Todos'); render();});}
function pass(c){const q=state.q; return (!cat()||c.categoria===cat())&&(!state.empresa.length||state.empresa.includes(c.empresa))&&(!state.numero.length||state.numero.includes(c.numero))&&(!state.unidade.length||state.unidade.includes(c.unidade))&&(!state.gc.length||state.gc.includes(c.grandeComando))&&(!state.ordenador.length||state.ordenador.includes(c.ordenador))&&(!state.acao.length||state.acao.includes(c.acao))&&(!state.moeda.length||state.moeda.includes(c.moeda))&&(!state.vigencia.length||state.vigencia.includes(c.vigencia))&&(!q||JSON.stringify(c).toLowerCase().includes(q));}
function groupedValues(rows){return [{label:'Valor contratado',value:sum(rows,'valorContrato')},{label:'Total empenhado USD',value:sum(rows,'totalEmpenhadoUsd')},{label:'Total faturado USD',value:sum(rows,'totalFaturadoUsd')},{label:'Valor disponível para empenho',value:sum(rows,'valorAEmpenhar')}];}
function plot(rows){const el=byId('contractsValueChart')||byId('contractValuesChart')||document.querySelector('[id*="Chart"]'); if(!el||!window.Plotly)return; const g=groupedValues(rows); Plotly.newPlot(el,[{type:'bar',x:g.map(x=>x.label),y:g.map(x=>x.value),text:g.map(x=>usd(x.value)),hovertemplate:'%{x}<br>%{y:$,.2f}<extra></extra>'}],{title:'Valores gerenciais dos contratos',margin:{l:70,r:20,t:50,b:80},height:380,yaxis:{tickprefix:'US$ ',separatethousands:true}}, {responsive:true,displayModeBar:false});}
function table(rows){const tb=byId('contractsTableBody')||document.querySelector('tbody[data-contracts-table]')||document.querySelector('.contracts-table tbody'); if(!tb)return; tb.innerHTML=rows.map(c=>'<tr><td>'+esc(c.numero||c.contrato)+'</td><td>'+esc(c.empresa)+'</td><td>'+esc(c.unidade)+'</td><td>'+esc(c.grandeComando)+'</td><td>'+esc(c.vigencia)+(c.riscoVigencia?' <span class="risk-flag">RISCO</span>':'')+'</td><td class="text-right">'+usd(c.valorContrato)+'</td><td class="text-right">'+usd(c.totalEmpenhadoUsd)+'</td><td class="text-right">'+usd(c.totalFaturadoUsd)+'</td><td>'+esc(c.objeto)+'</td></tr>').join('') || '<tr><td colspan="9">Sem contratos no filtro atual.</td></tr>';}
function mobile(rows){const el=byId('contractsMobileCards')||document.querySelector('.contracts-mobile-list'); if(!el)return; el.innerHTML=rows.slice(0,80).map(c=>'<article class="contract-mobile-card"><h3>'+esc(c.numero||c.contrato)+'</h3><p>'+esc(c.empresa)+'</p><dl><dt>Valor</dt><dd>'+usd(c.valorContrato)+'</dd><dt>Vigência</dt><dd>'+esc(c.vigencia)+'</dd><dt>Unidade</dt><dd>'+esc(c.unidade)+'</dd></dl></article>').join('');}
function renderOverview(){if(!document.querySelector('[data-contract-overview]'))return; const s=DATA.summary||{}; const total=DATA.contracts.length; const count=document.querySelector('[data-all-contracts-count]'); if(count)count.textContent=total.toLocaleString(BR); const paid=document.querySelector('[data-all-contracts-paid]'); if(paid)paid.textContent=usd((s.totals||{}).totalEmpenhadoUsd||sum(DATA.contracts,'totalEmpenhadoUsd')); document.querySelectorAll('[data-contract-summary]').forEach(card=>{const k=card.dataset.contractSummary; const rows=DATA.contracts.filter(c=>c.categoria===k); const c=card.querySelector('[data-summary-count]'); if(c)c.textContent=rows.length.toLocaleString(BR); const v=card.querySelector('[data-summary-value]'); if(v)v.textContent=usd(sum(rows,'valorContrato')); const p=card.querySelector('[data-summary-paid]'); if(p)p.textContent=usd(sum(rows,'totalEmpenhadoUsd'));});}
function render(){renderOverview(); const rows=DATA.contracts.filter(pass); document.querySelectorAll('[data-kpi="count"]').forEach(e=>e.textContent=rows.length.toLocaleString(BR)); document.querySelectorAll('[data-kpi="value"]').forEach(e=>e.textContent=usd(sum(rows,'valorContrato'))); document.querySelectorAll('[data-kpi="paidUsd"]').forEach(e=>e.textContent=usd(sum(rows,'totalEmpenhadoUsd'))); document.querySelectorAll('[data-kpi="billedUsd"]').forEach(e=>e.textContent=usd(sum(rows,'totalFaturadoUsd'))); plot(rows); table(rows); mobile(rows);}
document.addEventListener('DOMContentLoaded',()=>{initFilters();render();});
})();
