
(function(){
'use strict';
const DATA=window.CABW_CREDIT_DATA||{digits:[],pos:[],signing:[]};
const BR='pt-BR';
const money=new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const dec=new Intl.NumberFormat(BR,{maximumFractionDigits:2});
const pct=new Intl.NumberFormat(BR,{style:'percent',maximumFractionDigits:2});
function usd(x){return 'US$ '+money.format(+x||0)}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function byId(id){return document.getElementById(id)}
function unique(arr){return Array.from(new Set(arr.filter(Boolean))).sort((a,b)=>String(a).localeCompare(String(b),'pt-BR'))}
function sum(arr,key){return arr.reduce((a,b)=>a+(+b[key]||0),0)}
function short(s,n=20){s=String(s||'');return s.length>n?s.slice(0,n)+'...':s}
let state={ug:[],acao:[],natureza:[],projeto:[]};
function makeMulti(selId, options, key){const sel=byId(selId); if(!sel)return; const parent=sel.parentElement; sel.style.display='none'; const wrap=document.createElement('div'); wrap.className='cabw-multi-dropdown'; wrap.innerHTML='<button type="button" class="multi-toggle cabw-multi-toggle"><span>Todos</span><span>▾</span></button><div class="multi-menu cabw-multi-menu"><div class="cabw-multi-actions"><button type="button" data-act="all">Marcar todas</button><button type="button" data-act="clear">Limpar</button></div></div>'; parent.appendChild(wrap); const menu=wrap.querySelector('.cabw-multi-menu'); options.forEach(opt=>{const lab=document.createElement('label'); lab.className='cabw-multi-option'; lab.innerHTML='<input type="checkbox" value="'+esc(opt)+'"><span>'+esc(opt)+'</span>'; menu.appendChild(lab);}); const btn=wrap.querySelector('.cabw-multi-toggle'); function update(){const vals=Array.from(menu.querySelectorAll('input:checked')).map(x=>x.value); state[key]=vals; btn.querySelector('span').textContent=vals.length? (vals.length===1?short(vals[0],28):vals.length+' selecionados') : 'Todos'; render();} btn.addEventListener('click',e=>{e.stopPropagation();wrap.classList.toggle('is-open')}); menu.addEventListener('change',update); menu.addEventListener('click',e=>{if(e.target.dataset.act==='all'){menu.querySelectorAll('input').forEach(i=>i.checked=true);update()} if(e.target.dataset.act==='clear'){menu.querySelectorAll('input').forEach(i=>i.checked=false);update()}}); document.addEventListener('click',e=>{if(!wrap.contains(e.target))wrap.classList.remove('is-open')});}
function initFilters(){makeMulti('creditFilterUg', unique(DATA.digits.map(d=>d.om)), 'ug'); makeMulti('creditFilterAcao', unique(DATA.digits.map(d=>d.acao)), 'acao'); makeMulti('creditFilterNatureza', unique(DATA.digits.map(d=>d.natureza)), 'natureza'); makeMulti('creditFilterProjeto', unique(DATA.digits.map(d=>d.projetoLabel)), 'projeto'); const clr=byId('clearCreditFilters'); if(clr)clr.addEventListener('click',()=>{document.querySelectorAll('.cabw-multi-dropdown input').forEach(i=>i.checked=false); state={ug:[],acao:[],natureza:[],projeto:[]}; document.querySelectorAll('.cabw-multi-toggle span:first-child').forEach(s=>s.textContent='Todos'); render();});}
function passD(d){return (!state.ug.length||state.ug.includes(d.om))&&(!state.acao.length||state.acao.includes(d.acao))&&(!state.natureza.length||state.natureza.includes(d.natureza))&&(!state.projeto.length||state.projeto.includes(d.projetoLabel));}
function passPO(p){return (!state.ug.length||state.ug.includes(p.om))&&(!state.acao.length||state.acao.includes(p.acao))&&(!state.natureza.length||state.natureza.includes(p.natureza))&&(!state.projeto.length||state.projeto.includes(p.projetoLabel));}
function filtered(){return {digits:DATA.digits.filter(passD), pos:DATA.pos.filter(p=>String(p.data||'').startsWith('2026')&&passPO(p)), signing:DATA.signing.filter(passPO)};}
function group(rows,key,valkey){const m=new Map(); rows.forEach(r=>{const k=r[key]||'Não informado'; const cur=m.get(k)||0; m.set(k,cur+(+r[valkey]||0));}); return Array.from(m,([label,value])=>({label,value})).sort((a,b)=>b.value-a.value);}
function tableRows(rows, cols){return rows.map(r=>'<tr>'+cols.map(c=>'<td class="'+(c.num?'text-right':'')+'">'+esc(c.f?c.f(r):r[c.k])+'</td>').join('')+'</tr>').join('') || '<tr><td colspan="12">Sem registros para os filtros selecionados.</td></tr>'}
function plotBar(id, title, rows){const el=byId(id); if(!el||!window.Plotly)return; rows=rows.slice(0,18); Plotly.newPlot(el,[{type:'bar',orientation:'h',y:rows.map(r=>short(r.label)),x:rows.map(r=>r.value),text:rows.map(r=>usd(r.value)),customdata:rows.map(r=>r.label),hovertemplate:'%{customdata}<br>%{x:$,.2f}<extra></extra>'}],{title,margin:{l:170,r:20,t:45,b:40},height:Math.max(340,rows.length*28),xaxis:{tickprefix:'US$ ',separatethousands:true},yaxis:{automargin:true}}, {responsive:true,displayModeBar:false});}
function plotPie(id,title,rows){const el=byId(id); if(!el||!window.Plotly)return; rows=rows.slice(0,10); Plotly.newPlot(el,[{type:'pie',labels:rows.map(r=>short(r.label)),values:rows.map(r=>r.value),customdata:rows.map(r=>r.label),hovertemplate:'%{customdata}<br>%{value:$,.2f}<br>%{percent}<extra></extra>'}],{title,margin:{l:20,r:20,t:45,b:20},height:360}, {responsive:true,displayModeBar:false});}
function render(){const f=filtered(); const avail=sum(f.digits,'saldo'), committed=sum(f.pos,'valorUsd'), signing=sum(f.signing,'valor'), received=avail+committed+signing; if(byId('kpiCreditAvailable'))byId('kpiCreditAvailable').textContent=usd(avail); if(byId('kpiCommitted'))byId('kpiCommitted').textContent=usd(committed); if(byId('kpiSigning'))byId('kpiSigning').textContent=usd(signing); if(byId('kpiReceived'))byId('kpiReceived').textContent=usd(received); if(byId('kpiAvailablePct'))byId('kpiAvailablePct').textContent=pct.format(received?avail/received:0); if(byId('kpiDigitsCount'))byId('kpiDigitsCount').textContent=f.digits.length.toLocaleString(BR); if(byId('executiveSummaryBody'))byId('executiveSummaryBody').innerHTML='<tr><td>2026</td><td class="text-right">'+usd(avail)+'</td><td class="text-right">'+usd(committed)+'</td><td class="text-right">'+usd(signing)+'</td><td class="text-right">'+usd(received)+'</td><td class="text-center">'+pct.format(received?avail/received:0)+'</td><td class="text-center">'+f.digits.length.toLocaleString(BR)+'</td></tr>'; if(byId('digitsListBody'))byId('digitsListBody').innerHTML=tableRows(f.digits,[{k:'digito'},{k:'om'},{k:'acao'},{k:'natureza'},{k:'projetoLabel'},{k:'saldo',num:1,f:r=>usd(r.saldo)},{k:'objetivo'}]); plotPie('creditByGcChart','Crédito disponível por Grande Comando',group(f.digits,'gc','saldo')); plotPie('poByGcChart','POs por Grande Comando',group(f.pos,'gc','valorUsd')); plotBar('poByCompanyChart','Empenhos por empresa',group(f.pos,'nomeFornecedor','valorUsd')); plotBar('poByProjectChart','Empenhos por projeto',group(f.pos,'projetoLabel','valorUsd')); const ug=group(f.digits,'om','saldo'); plotBar('ugChart','Crédito disponível por OM',ug); if(byId('ugTableBody'))byId('ugTableBody').innerHTML=tableRows(ug,[{k:'label'},{k:'value',num:1,f:r=>usd(r.value)}]); const ac=group(f.digits,'acao','saldo'); plotBar('actionChart','Crédito disponível por ação',ac); if(byId('actionTableBody'))byId('actionTableBody').innerHTML=tableRows(ac,[{k:'label'},{k:'value',num:1,f:r=>usd(r.value)}]); if(byId('detailKpiCredit'))byId('detailKpiCredit').textContent=usd(avail); if(byId('detailKpiUgs'))byId('detailKpiUgs').textContent=unique(f.digits.map(d=>d.om)).length; if(byId('detailKpiActions'))byId('detailKpiActions').textContent=unique(f.digits.map(d=>d.acao)).length; if(byId('detailTableBody'))byId('detailTableBody').innerHTML=tableRows(f.digits,[{k:'digito'},{k:'om'},{k:'acao'},{k:'ptres'},{k:'natureza'},{k:'projetoLabel'},{k:'saldo',num:1,f:r=>usd(r.saldo)},{k:'objetivo'}]); if(byId('consistencyTableBody'))byId('consistencyTableBody').innerHTML=tableRows([{a:'Dígitos carregados',v:DATA.digits.length,o:'digitos.xlsx'},{a:'Saldo disponível total',v:usd(sum(DATA.digits,'saldo')),o:'Soma dos saldos'},{a:'POs 2026',v:DATA.pos.filter(p=>String(p.data||'').startsWith('2026')).length,o:'ordem_de_compra.xlsx'},{a:'POs em assinatura consideradas',v:DATA.signing.length,o:'AMEND desconsiderado'}],[{k:'a'},{k:'v'},{k:'o'}]);}
document.addEventListener('DOMContentLoaded',()=>{initFilters();render();});
})();
