
(function(){
'use strict';
const data=window.CABW_CREDIT_DATA||{digits:[],purchaseOrders:[],signatureOrders:[],meta:{}};
const $=(s,c)=> (c||document).querySelector(s); const $all=(s,c)=>Array.from((c||document).querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>'US$ '+Number(v||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const num=v=>Number(v||0).toLocaleString('pt-BR');
const pct=(a,b)=> b ? ((a/b)*100).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})+'%' : '0,00%';
function selected(sel){if(!sel)return []; return Array.from(sel.selectedOptions).map(o=>o.value).filter(Boolean);}
function unique(a){return Array.from(new Set(a.filter(v=>v!==undefined&&v!==null&&String(v).trim()!==''))).sort((a,b)=>String(a).localeCompare(String(b),'pt-BR'));}
function omLabel(r){return r.omLabel || [r.sigla,r.nomeUgr].filter(Boolean).join(' - ') || 'N/I';}
function projectLabels(r){ if(Array.isArray(r.projetosLabels)&&r.projetosLabels.length) return r.projetosLabels; if(r.projetoLabel)return [r.projetoLabel]; if(Array.isArray(r.projetos))return r.projetos; if(r.projeto)return [r.projeto]; return [];}
function hasAny(rowVals, selectedVals){ return !selectedVals.length || selectedVals.some(v=>rowVals.includes(v)); }
function filters(){return {ug:selected($('#creditFilterUg')), acao:selected($('#creditFilterAcao')), natureza:selected($('#creditFilterNatureza')), projeto:selected($('#creditFilterProjeto'))};}
function rowMatches(r,f){return (!f.ug.length||f.ug.includes(omLabel(r))) && (!f.acao.length||f.acao.includes(r.acao||'')) && (!f.natureza.length||f.natureza.includes(r.natureza||'')) && hasAny(projectLabels(r), f.projeto);}
function filtered(){const f=filters(); return {digits:data.digits.filter(r=>rowMatches(r,f)), pos:data.purchaseOrders.filter(r=>rowMatches(r,f)), sig:data.signatureOrders.filter(r=>rowMatches(r,f)), f};}
function fillMulti(sel, vals){ if(!sel)return; const old=selected(sel); sel.multiple=true; sel.size=Math.min(6, Math.max(3, vals.length+1)); sel.classList.add('cabw-multi-select'); sel.innerHTML=vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join(''); old.forEach(v=>{const o=Array.from(sel.options).find(o=>o.value===v); if(o)o.selected=true;}); }
function initFilters(){ const d=data.digits||[], p=data.purchaseOrders||[], s=data.signatureOrders||[]; fillMulti($('#creditFilterUg'), unique([].concat(d.map(omLabel),p.map(omLabel),s.map(omLabel))).filter(v=>!/^[0-9]+$/.test(String(v).trim()))); fillMulti($('#creditFilterAcao'), unique([].concat(d.map(r=>r.acao),p.map(r=>r.acao),s.map(r=>r.acao)))); fillMulti($('#creditFilterNatureza'), unique([].concat(d.map(r=>r.natureza),p.map(r=>r.natureza),s.map(r=>r.natureza)))); fillMulti($('#creditFilterProjeto'), unique([].concat(...d.map(projectLabels),...p.map(projectLabels),...s.map(projectLabels)))); $all('#creditFilterUg,#creditFilterAcao,#creditFilterNatureza,#creditFilterProjeto').forEach(el=>el.addEventListener('change', renderAll)); $('#clearCreditFilters')?.addEventListener('click',()=>{$all('#creditFilterUg,#creditFilterAcao,#creditFilterNatureza,#creditFilterProjeto').forEach(e=>Array.from(e.options).forEach(o=>o.selected=false)); renderAll();}); }
function agg(arr, keyFn, valFn){const m=new Map(); arr.forEach(r=>{const k=keyFn(r)||'N/I'; m.set(k,(m.get(k)||0)+Number(valFn(r)||0));}); return Array.from(m,([label,value])=>({label,value})).sort((a,b)=>b.value-a.value);}
function drawPie(id, rows, title){const el=$('#'+id); if(!el)return; if(!window.Plotly){el.innerHTML='<p>Plotly não carregado.</p>';return;} Plotly.newPlot(el,[{type:'pie',labels:rows.map(r=>r.label),values:rows.map(r=>r.value),textinfo:'label+percent',hovertemplate:'%{label}<br>'+title+': %{value:$,.2f}<extra></extra>'}],{title:{text:title,font:{size:16}},height:360,margin:{l:20,r:20,t:60,b:20}}, {displayModeBar:false,responsive:true});}
function drawBar(id, rows, title, yTitle){const el=$('#'+id); if(!el)return; if(!window.Plotly){el.innerHTML='<p>Plotly não carregado.</p>';return;} const top=rows.filter(r=>Number(r.value)>0).slice(0,20).reverse(); Plotly.newPlot(el,[{type:'bar',orientation:'h',y:top.map(r=>r.label),x:top.map(r=>r.value),text:top.map(r=>money(r.value)),textposition:'auto',hovertemplate:'%{y}<br>Valor: %{x:$,.2f}<extra></extra>',marker:{color:'#003b7a'}}],{title:{text:title,font:{size:16}},height:Math.max(360,top.length*26+120),margin:{l:170,r:30,t:60,b:50},xaxis:{title:yTitle||'US$'}}, {displayModeBar:false,responsive:true});}
function renderExecutive(){ if(!$('#kpiCreditAvailable')) return; const {digits,pos,sig}=filtered(); const credito=digits.reduce((a,r)=>a+Number(r.saldo||0),0); const empenhado=pos.reduce((a,r)=>a+Number(r.valorUsd||0),0); const assinatura=sig.reduce((a,r)=>a+Number(r.valorUsd||0),0); const total=credito+empenhado+assinatura; $('#kpiCreditAvailable').textContent=money(credito); $('#kpiCommitted').textContent=money(empenhado); $('#kpiSigning').textContent=money(assinatura); $('#kpiReceived').textContent=money(total); $('#kpiAvailablePct').textContent=pct(credito,total); $('#kpiDigitsCount').textContent=num(digits.length); const table=$('#executiveSummaryBody'); if(table)table.innerHTML=`<tr><td>2026</td><td class="text-right">${money(credito)}</td><td class="text-right">${money(empenhado)}</td><td class="text-right">${money(assinatura)}</td><td class="text-right">${money(total)}</td><td class="text-center">${pct(credito,total)}</td><td class="text-center">${num(digits.length)}</td></tr>`; drawPie('creditByGcChart', agg(digits, r=>r.gcDescricao||r.grandComando||'N/I', r=>r.saldo), 'Crédito disponível por Grande Comando'); drawPie('poByGcChart', agg(pos, r=>r.gcDescricao||r.grandComando||'N/I', r=>r.valorUsd), 'PO por Grande Comando'); drawBar('poByCompanyChart', agg(pos, r=>r.fornecedor||'N/I', r=>r.valorUsd), 'Empenhos por empresa', 'Valor empenhado'); drawBar('poByProjectChart', agg(pos, r=>projectLabels(r).join(', ')||'Sem projeto', r=>r.valorUsd), 'Empenhos por projeto', 'Valor empenhado'); renderDigitsTable(digits); }
function renderDigitsTable(digits){const tb=$('#digitsListBody'); if(!tb)return; tb.innerHTML=digits.slice().sort((a,b)=>Number(b.saldo||0)-Number(a.saldo||0)).map(r=>`<tr><td>${esc(r.digito)}</td><td>${esc(omLabel(r))}</td><td>${esc(r.acao)}</td><td>${esc(r.natureza)}</td><td>${esc(projectLabels(r).join(', '))}</td><td class="text-right">${money(r.saldo)}</td><td>${esc(r.objetivo)}</td></tr>`).join('');}
function renderUG(){ if(!$('#ugChart') && !$('#ugTableBody'))return; const {digits}=filtered(); const rows=agg(digits, r=>r.sigla||omLabel(r), r=>r.saldo); if(window.Plotly&&$('#ugChart')) drawBar('ugChart', rows, 'Crédito disponível por OM', 'Saldo disponível'); const body=$('#ugTableBody'); if(body) body.innerHTML=rows.map(r=>`<tr><td>${esc(r.label)}</td><td class="text-right">${money(r.value)}</td></tr>`).join(''); }
function renderAction(){ if(!$('#actionChart') && !$('#actionTableBody'))return; const {digits}=filtered(); const rows=agg(digits, r=>r.acao||'Sem ação', r=>r.saldo); if(window.Plotly&&$('#actionChart')) drawBar('actionChart', rows, 'Crédito disponível por ação', 'Saldo disponível'); const body=$('#actionTableBody'); if(body) body.innerHTML=rows.map(r=>`<tr><td>${esc(r.label)}</td><td class="text-right">${money(r.value)}</td></tr>`).join(''); }
function renderDetail(){ if(!$('#detailTableBody'))return; const {digits}=filtered(); const total=digits.reduce((a,r)=>a+Number(r.saldo||0),0); $('#detailKpiCredit')&&($('#detailKpiCredit').textContent=money(total)); $('#detailKpiUgs')&&($('#detailKpiUgs').textContent=num(unique(digits.map(omLabel)).length)); $('#detailKpiActions')&&($('#detailKpiActions').textContent=num(unique(digits.map(r=>r.acao)).length)); $('#detailTableBody').innerHTML=digits.sort((a,b)=>Number(b.saldo||0)-Number(a.saldo||0)).map(r=>`<tr><td>${esc(r.digito)}</td><td>${esc(omLabel(r))}</td><td>${esc(r.acao)}</td><td>${esc(r.ptres)}</td><td>${esc(r.natureza)}</td><td>${esc(projectLabels(r).join(', '))}</td><td class="text-right">${money(r.saldo)}</td><td>${esc(r.objetivo)}</td></tr>`).join(''); }
function renderConsistency(){ if(!$('#consistencyTableBody'))return; const all=data.digits||[]; const total=all.reduce((a,r)=>a+Number(r.saldo||0),0); $('#consistencyTableBody').innerHTML=`<tr><td>Total de dígitos carregados</td><td class="text-right">${num(all.length)}</td><td>Fonte: ${esc(data.meta.sourceDigits||'digitos.xlsx')}</td></tr><tr><td>Saldo total disponível</td><td class="text-right">${money(total)}</td><td>Dígitos filtráveis por OM e projeto descritivos</td></tr>`;}
function renderAll(){renderExecutive();renderUG();renderAction();renderDetail();renderConsistency();}
document.addEventListener('DOMContentLoaded',()=>{try{initFilters(); renderAll();}catch(e){console.error('CABW credit error',e);}});
})();
